### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by dariusptrs** [latex4ei/latex4ei-packages#8]
for our gh-actions workflows to use the latest version of this

**Comment by hofbi** [comment]
What exactly should I do here? Update the docker image uesed [here](https://github.com/latex4ei/latex4ei-packages/blob/master/.github/workflows/ci.yml#L15)?

**Comment by dariusptrs** [comment]
Yes, so that the issues hyperlink is included in the pdfs we are building with that container.

**Comment by hofbi** [comment]
Done: https://hub.docker.com/r/makeappdev/uselatex
